"""initial_schema

Revision ID: ee63f0cec60d
Revises: 
Create Date: 2026-03-14 18:01:46.459772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ee63f0cec60d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('name_en', sa.String(length=512), nullable=True),
    sa.Column('department', sa.String(length=256), nullable=True),
    sa.Column('faculty', sa.String(length=256), nullable=True),
    sa.Column('lab_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labs_name'), 'labs', ['name'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'url', name='uq_datasource_lab_url')
    )
    op.create_index(op.f('ix_data_sources_lab_id'), 'data_sources', ['lab_id'], unique=False)
    op.create_table('embedding_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_embedding_chunks_embedding_cosine', 'embedding_chunks', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_embedding_chunks_lab_id'), 'embedding_chunks', ['lab_id'], unique=False)
    op.create_table('professors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('name_en', sa.String(length=256), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lab_id', 'name', name='uq_professor_lab_name')
    )
    op.create_index(op.f('ix_professors_lab_id'), 'professors', ['lab_id'], unique=False)
    op.create_table('research_themes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['labs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_themes_lab_id'), 'research_themes', ['lab_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_themes_lab_id'), table_name='research_themes')
    op.drop_table('research_themes')
    op.drop_index(op.f('ix_professors_lab_id'), table_name='professors')
    op.drop_table('professors')
    op.drop_index(op.f('ix_embedding_chunks_lab_id'), table_name='embedding_chunks')
    op.drop_index('ix_embedding_chunks_embedding_cosine', table_name='embedding_chunks', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('embedding_chunks')
    op.drop_index(op.f('ix_data_sources_lab_id'), table_name='data_sources')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_labs_name'), table_name='labs')
    op.drop_table('labs')
    # ### end Alembic commands ###
